### ISSUE TITLE
Error during attempt to load integration.

### ISSUE THREAD

**Issue by vikreh** [thomasloven/hass-plejd#62]
Logger: homeassistant.loader
Source: custom_components/plejd/__init__.py:13
Integration: Plejd BLE ([documentation](https://github.com/thomasloven/hass_plejd), [issues](https://github.com/thomasloven/hass_plejd/issues))
First occurred: 23:37:43 (6 occurrences)
Last logged: 23:47:33

Unexpected exception importing platform custom_components.plejd.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/plejd/__init__.py", line 13, in <module>
    PLATFORMS = [Platform.LIGHT, Platform.SWITCH, Platform.SCENE, Platform.EVENT, Platform.BINARY_SENSOR]
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: EVENT

**Comment by thomasloven** [comment]
Which Home Assistant version are you using?

**Comment by vikreh** [comment]
Hi, 2023.7.3 running HA Core on Ubuntu based system. Probably on Python
3.10.6 if that is important. I might need to confirm that though.

Den lör 30 mars 2024 00:01Thomas Lovén ***@***.***> skrev:
