### ISSUE TITLE
error setup intergration

### ISSUE THREAD

**Issue by arnoslag** [thomasloven/hass-plejd#63]
it discoverd the plejd  ble, i can login, shows my  home and 15 devices. Then  no devices are entities.
 running HA core  2024.5.1

Error log

2024-05-05 08:51:42.275 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry #### for plejd
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plejd/__init__.py", line 31, in async_setup_entry
    await site.start()
  File "/config/custom_components/plejd/plejd_site.py", line 83, in start
    await self.manager.init(cached_site_data)
  File "/usr/local/lib/python3.12/site-packages/pyplejd/__init__.py", line 56, in init
    self.devices = self.cloud.devices
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplejd/cloud/__init__.py", line 214, in devices
    PlejdDevice(
  File "/usr/local/lib/python3.12/site-packages/pyplejd/interface.py", line 48, in __init__
    super().__init__(**data)
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for PlejdDevice
outputType
  unexpected value; permitted: 'LIGHT', 'SENSOR', 'RELAY', 'MOTION', 'UNKNOWN' (type=value_error.const; given=COVERABLE; permitted=('LIGHT', 'SENSOR', 'RELAY', 'MOTION', 'UNKNOWN'))

**Comment by oyvindwe** [comment]
@arnoslag Which devices do you have?

I have submitted a possible fix to `pyplejd`. Are you able to test it?

**Comment by arnoslag** [comment]
Sure i can test it

I got these plejd devices
REL-01-2P
WRT-01
DIMM-02
WPH-01
DWN-01
REL-02
LED-75
JAL-01
WIN-01
DIM-01
GWY-01

Op wo 8 mei 2024 om 00:22 schreef Øyvind Matheson Wergeland <
***@***.***>:

**Comment by thomasloven** [comment]
It's likely the JAL-01 which is the problem.
Where did you manage to pick that one up?

**Comment by arnoslag** [comment]
It is in beta right now the JAL-01

**Comment by arnoslag** [comment]
> It's likely the JAL-01 which is the problem. I assume you are a beta tester?

Yes i'm beta tester. I did remove the Jal switch fro plejd app. and now i works
