### ISSUE TITLE
jal-01 still unsuported

### ISSUE THREAD

**Issue by chris150890** [thomasloven/hass-plejd#67]
the jal-01 is still unsupported. 

got error:

Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 20:39:20 (4 occurrences)
Last logged: 20:45:21

Error setting up entry Thuis for plejd
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plejd/__init__.py", line 31, in async_setup_entry
    await site.start()
  File "/config/custom_components/plejd/plejd_site.py", line 83, in start
    await self.manager.init(cached_site_data)
  File "/usr/local/lib/python3.12/site-packages/pyplejd/__init__.py", line 56, in init
    self.devices = self.cloud.devices
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplejd/cloud/__init__.py", line 214, in devices
    PlejdDevice(
  File "/usr/local/lib/python3.12/site-packages/pyplejd/interface.py", line 48, in __init__
    super().__init__(**data)
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for PlejdDevice
outputType
  unexpected value; permitted: 'LIGHT', 'SENSOR', 'RELAY', 'MOTION', 'UNKNOWN' (type=value_error.const; given=COVERABLE; permitted=('LIGHT', 'SENSOR', 'RELAY', 'MOTION', 'UNKNOWN'))

**Comment by thomasloven** [comment]
It looks like the update to the latest release failed for some reason.
Because this:
> File "/usr/local/lib/python3.12/site-packages/pyplejd/cloud/init.py", line 214, in devices
> PlejdDevice(

is not what that line of that file says anymore.

Try removing and reinstalling the integration.

**Comment by thomasloven** [comment]
Actually, apparently I made a mistake in the latest release... Try 0.13.1
